
byd__Qt5__configure__add_args(${package} -system-zlib)
byd__Qt5__configure__add_args(${package} -system-libpng)
byd__Qt5__configure__add_args(${package} -system-libjpeg)
byd__Qt5__configure__add_args(${package} -qt-doubleconversion)
byd__Qt5__configure__add_args(${package} -qt-freetype)
byd__Qt5__configure__add_args(${package} -qt-harfbuzz)
byd__Qt5__configure__add_args(${package} -openssl)
byd__Qt5__configure__add_args(${package} -libproxy)
byd__Qt5__configure__add_args(${package} -qt-pcre)

byd__Qt5__configure__add_args(${package} -directwrite)
byd__Qt5__configure__add_args(${package} -opengl dynamic)
byd__Qt5__configure__add_args(${package} -audio-backend)
byd__Qt5__configure__add_args(${package} -mp)
